Repository PokemonWorkshop/PokemonStudio, pull requests merged in 2024-11, with the labels that each got.

#405 Implement change order feature for creatures in trainer party
  assets/i18n/de/database_trainers.json
  assets/i18n/en/database_trainers.json
  assets/i18n/en/editor.json
  assets/i18n/en/pokemon_battler_list.json
  assets/i18n/es/database_trainers.json
  assets/i18n/fr/database_trainers.json
  assets/i18n/fr/editor.json
  assets/i18n/fr/pokemon_battler_list.json
  assets/i18n/it/database_trainers.json
  assets/i18n/pt/database_trainers.json
  assets/icons/global/reorder.svg
  package-lock.json
  src/views/components/bagEntry/BagEntryList.tsx
  src/views/components/buttons/DarkButtonWithPlusIcon.tsx
  src/views/components/editor/Editor.tsx
  src/views/components/pokemonBattler/PokemonBattlerList.tsx
  src/views/components/pokemonBattler/editors/PokemonBattlerChangeOrder.tsx
  src/views/components/pokemonBattler/editors/PokemonBattlerEditor.tsx
  src/views/components/pokemonBattler/editors/PokemonBattlerEditorOverlay.tsx
  src/views/components/pokemonBattler/editors/PokemonBattlerMoreInfoEditor.tsx
  src/views/components/pokemonBattler/editors/index.tsx
  src/views/components/pokemonBattler/editors/usePokemonBattler.ts
  src/views/pages/database/Trainer.page.tsx
Labels: user story

#406 Fix an issue with the translation of the creature form name
  src/views/components/database/pokemon/editors/InformationEditor/TranslatableFormTextFields.tsx
  src/views/components/database/pokemon/editors/InformationsEditor.tsx
Labels: bug

#407 Fix: Egg group unknown by default
  src/backendTasks/migrateData.ts
  src/migrations/migrateUndefinedBreedingGroupToUnknown.ts
  src/utils/entityCreation.ts
  src/views/components/database/pokemon/editors/BreedingEditor.tsx
  src/views/components/world/overview/ReactFlowOverview.tsx
Labels: bug

#413 Refactorize the migration code process
  assets/i18n/en/index.js
  assets/i18n/en/migration.json
  assets/i18n/fr/index.js
  assets/i18n/fr/migration.json
  package-lock.json
  package.json
  src/@types/react-i18n.d.ts
  src/backendTasks/migrateData.ts
  src/backendTasks/synchronizeLanguage.ts
  src/i18n.ts
  src/main/index.ts
  src/migrations/migrationConfig.ts
  src/preload.ts
  src/views/pages/Home.page.tsx
  src/views/pages/settings/Settings.language.page.tsx
Labels: technical story
