Repository PokemonWorkshop/PokemonStudio, pull requests merged in 2024-01, with the labels that each got.

#133 Feature: Make sure we can only delete a map on the map database UI in RMXP mode #121
  src/utils/useMapInfo.ts
  src/utils/usePage.ts
  src/views/components/database/dataBlocks/DataBlockContainer.tsx
  src/views/components/database/dataBlocks/DataBlockWithTitle.tsx
  src/views/components/database/type/editors/TypeNewEditor.tsx
  src/views/components/world/map/MapFrame.tsx
  src/views/components/world/map/MapMenu.tsx
  src/views/components/world/map/MapMusics.tsx
  src/views/components/world/map/tree/MapTreeComponent.tsx
  src/views/components/world/map/tree/MapTreeContextMenu.tsx
  src/views/pages/world/Map.page.tsx
Labels: technical story

#136 Remove the pokeiconshiny from the new project archive
  new-project.zip
Labels: technical story

#140 Make sure that the MapImport ignores the already existing map ID in RMXP
  src/utils/ModelUtils.ts
  src/utils/entityCreation.ts
  src/utils/useMapImport/index.ts
  src/utils/useMapImport/types.ts
  src/utils/useMapImport/useMapImportProcessor.ts
  src/utils/usePage.ts
  src/views/components/world/map/editors/MapImport/MapImport.tsx
Labels: technical story

#147 Fix some UX/UI issues on the texts translation UI
  src/views/components/textmanagement/TranslateAttachedTexts.tsx
  src/views/components/textmanagement/TranslateList.tsx
  src/views/components/textmanagement/TranslateTarget.tsx
  src/views/pages/texts/Translation.page.tsx
Labels: technical story

#163 Fix wrong data refresh in the DexPokemonListTable component
  src/views/components/database/dex/editors/DexPokemonListImportEditor.tsx
  src/views/components/database/dex/table/DexPokemonListTable.tsx
  src/views/components/database/dex/table/RenderPokemon.tsx
  src/views/components/selects/SelectDex.tsx
Labels: bug

#170 Fix: The translation UI that crash if only one language is in the CSV
  src/utils/usePage.ts
  src/utils/useProjectSavingLanguage.ts
  src/views/components/dashboard/editors/DashboardLanguageNewEditor.tsx
  src/views/components/database/DatabaseTabsBar.tsx
  src/views/components/textmanagement/TextList.tsx
  src/views/pages/texts/BaseTexts.page.tsx
  src/views/pages/texts/Texts.page.tsx
Labels: bug

#183 Fix: Resource placeholder not displayed in release
  assets/i18n/en/text_management.json
  assets/i18n/es/text_management.json
  assets/i18n/fr/text_management.json
  forge.config.ts
  package.json
  placeholder.svg
  src/main/index.ts
  src/utils/electronProtocol.ts
Labels: bug

#190 UI: Add map page empty state
  assets/i18n/en/database_maps.json
  assets/i18n/fr/database_maps.json
  src/views/components/pages/PageEmptyState.tsx
  src/views/components/pages/index.tsx
  src/views/components/world/map/MapEmptyState.tsx
  src/views/components/world/map/editors/MapImport/MapImportOverlay.tsx
  src/views/components/world/map/index.tsx
  src/views/pages/world/Map.page.tsx
Labels: user story

#180 Feature: Add the new project download service
  .gitignore
  assets/i18n/en/loader.json
  assets/i18n/fr/loader.json
  forge.config.ts
  new-project.zip
  package-lock.json
  package.json
  src/backendTasks/calculateFileSha1.ts
  src/backendTasks/checkDownloadNewProject.ts
  src/backendTasks/checkMapsModified.ts
  src/backendTasks/copyTiledFiles.ts
  src/backendTasks/downloadFile.ts
  src/backendTasks/extractNewProject.ts
  src/backendTasks/requestJson.ts
  src/main/index.ts
  src/preload.ts
  src/utils/downloadSpeed.ts
  src/utils/useProjectNew/types.ts
  src/utils/useProjectNew/useProjectNewProcessor.ts
Labels: user story
