Repository PokemonWorkshop/PokemonStudio, pull requests merged in 2024-04, with the labels that each got.

#272 Feature: Implement an UI component for the user onboarding flow
  assets/i18n/en/index.js
  assets/i18n/en/onboarding.json
  assets/i18n/fr/index.js
  assets/i18n/fr/onboarding.json
  assets/icons/global/success-onboarding.svg
  src/@types/react-i18n.d.ts
  src/main/index.ts
  src/preload.ts
  src/utils/onboarding.ts
  src/utils/useDefaultTextInfoTranslation.ts
  src/views/components/buttons/GenericButtons.tsx
  src/views/components/onboarding/Onboarding.tsx
  src/views/components/onboarding/OnboardingBlock.tsx
  src/views/pages/dashboard/Dashboard.page.tsx
Labels: user story

#279 Fix Pokémon icon, rareness and given name in PokemonBattler editors
  src/utils/path.ts
  src/views/components/pokemonBattler/editors/PokemonBattlerMoreInfoEditor.tsx
  src/views/components/pokemonBattler/editors/usePokemonBattler.ts
Labels: bug

#281 Fix the MapImport for the user using subfolders for the maps
  src/backendTasks/copyTiledFiles.ts
Labels: bug

#271 fix: make JSON more easy to debug
  .vscode/settings.json
  src/backendTasks/RMXP2StudioMapsSync.ts
  src/backendTasks/configureNewProject.ts
  src/backendTasks/copyTiledFiles.ts
  src/backendTasks/migrateData.ts
  src/backendTasks/readMaps.ts
  src/backendTasks/readProjectConfigs.ts
  src/backendTasks/readProjectData.ts
  src/backendTasks/readProjectMetadata.ts
  src/backendTasks/saveProjectTexts.ts
  src/backendTasks/saveRMXPMapInfo.ts
  src/backendTasks/studioMapToRMXPConversionFacilitator.ts
  src/backendTasks/updateTextInfos.ts
  src/i18n.ts
  src/migrations/addAvailableLanguagesForTranslation.ts
  src/migrations/addMoveCharacteristics.ts
  src/migrations/addStepsAverageToGroup.ts
  src/migrations/addVolumeAndPitchInMaps.ts
  src/migrations/fixBeMethodMoveSelfStatus.ts
  src/migrations/fixCsvFileIdDex.ts
  src/migrations/generatingMapOverviews.ts
  src/migrations/linkResourcesToCreatures.ts
  src/migrations/mapRGSSObject.ts
  src/migrations/migrateHeadbutt.ts
  src/migrations/trainersResources.ts
  src/utils/SerializationUtils.ts
  src/utils/cloneEntity.ts
  src/utils/generateSelectedIdentifier.ts
  src/utils/json/parse.ts
  src/utils/projectList.ts
  src/utils/useMapImport/useMapImportProcessor.ts
  src/utils/useProjectLoad/helpers.ts
  src/utils/useRMXP2StudioMapsUpdate/useRMXP2StudioMapsUpdateProcessor.ts
  src/views/components/error/ErrorDialog.tsx
Labels: bug, accessibility

#275 Implement credits UI parts
  assets/i18n/de/dashboard_credits.json
  assets/i18n/de/index.js
  assets/i18n/en/dashboard_credits.json
  assets/i18n/en/index.js
  assets/i18n/es/dashboard_credits.json
  assets/i18n/es/index.js
  assets/i18n/fr/dashboard_credits.json
  assets/i18n/fr/index.js
  assets/i18n/it/dashboard_credits.json
  assets/i18n/it/index.js
  assets/i18n/pt/dashboard_credits.json
  assets/i18n/pt/index.js
  src/@types/react-i18n.d.ts
  src/views/components/dashboard/DashboardCredits.tsx
  src/views/components/dashboard/DashboardNavigation.tsx
  src/views/components/dashboard/index.tsx
  src/views/components/database/credits/editors/MemberEditEditor.tsx
  src/views/components/database/credits/editors/MemberNewEditor.tsx
  src/views/components/database/credits/tables/CreditMemberTableStyle.tsx
  src/views/components/database/credits/tables/CreditMembersTable.tsx
  src/views/components/database/credits/tables/RenderMember.tsx
  src/views/components/database/credits/tables/index.tsx
  src/views/components/inputs/EmbeddedUnitInput.tsx
  src/views/pages/dashboard/Dashboard.Credits.page.tsx
  src/views/pages/dashboard/Dashboard.Router.page.tsx
Labels: user story
