Repository PokemonWorkshop/PokemonStudio, pull requests merged in 2025-05, with the labels that each got.

#498 Add a project setting to manage the 3d battle camera mode from studio
  assets/i18n/de.json
  assets/i18n/en.json
  assets/i18n/es.json
  assets/i18n/fr.json
  assets/i18n/it.json
  assets/i18n/pt.json
  src/migrations/addBattleCamera3dToSettings.ts
  src/migrations/migrationConfig.ts
  src/models/entities/config.ts
  src/views/components/dashboard/DashboardSettings.tsx
Labels: User story

#493 Implement read RMXP events service
  src/backendTasks/readRMXPEvents.ts
  src/backendTasks/readRMXPMap.ts
  src/main/index.ts
  src/preload.ts
Labels: Technical story

#502 Fix the migration texts that are not displayed correctly
  assets/i18n/de.json
  assets/i18n/en.json
  assets/i18n/es.json
  assets/i18n/fr.json
  assets/i18n/it.json
  assets/i18n/pt.json
  src/backendTasks/migrateData.ts
  src/migrations/migrationConfig.ts
Labels: Bug

#495 Add a poc section and a poc for the event editor page
  assets/icons/navigation/adb-icon.svg
  config/webpack.main.config.ts
  config/webpack.renderer.config.ts
  src/App.tsx
  src/poc/Poc.router.tsx
  src/poc/PocHomePage.tsx
  src/poc/eventEditor/EventDnDContext.tsx
  src/poc/eventEditor/EventEditor.tsx
  src/views/components/icons/BaseIcon/BaseIcon.tsx
  src/views/components/navigation/NavigationBar/NavigationBar.tsx
  tsconfig.json
Labels: Technical story
